# Locators
LOGIN_BTN = "//p[contains(text(),'Log in')]"
SET_EMAIL = "//input[@name='username']"
SET_PASS = "//input[@name='password']"
CLICK_SIGNIN_BTN = "//button[@value='login']"
FORGOT_PASS_HYPERLINK = "//a[contains(text(),'Forgot password?')]"
Authentication_Method = "//select[@name='scheme']"
Select_Authentication_Method = "//option[contains(text(),'Non-J&J')]"
Studied_Dashboard = "(//span[contains(text(),'Studies')])[1]"
Close_Button = "(//button[contains(text(),'Close')])[1]"
Profile_icon = "//i[@class='user outline fitted icon']"
Profile_image = "//div[@class='sc-dxgOiQ hGcaOc']"
Email_id = "//div[@class='userColorIconContainer']"
Change_Pass_Icon = "//i[@class='key icon']"
Change_Pass_Hyper_link = "(//span[contains(text(),'Change password')])[1]"
Username_Email_PopUp = "//div[@class='loginForm']"
Username_Input_Text_Field = "//input[@placeholder='Username']"
Send_Email = "//button[contains(text(),'Send email')]"
LogOut_Icon = "//i[@class='sign out icon']"
LogOut_Hyper_link = "//span[contains(text(),'Log out')]"
Help_Icon = "(//div[@class='ui dropdown item navDropdown'])[2]"
My_Studies = "//a[@title='My studies']"
Created_New_To_Old = "(//div[@class='ui selection dropdown'])[2]"
My_Studies_All_Option_Selectable = "//div[@class='visible menu transition']"
About_Halo_link = "//div[contains(text(),'About HALO Link')]"
Studies_On_My_Studies = "(//span[@class='studyName'])[1]"
Click_On_Plus_Button_One = "4016"
Click_On_Plus_Button_Two = "3990"
Search_Field = "//input[@placeholder='Find Slides']"
Search_Option_Dropdown = "(//div[@role='listbox'])[1]"
Select_Slides = "//div[contains(text(),'Slides')]"
Select_Advanced_Search = "//a[@href='/s/search']"

