# Locators
LOGIN_BTN = "//p[contains(text(),'Log in')]"
SET_EMAIL = "//input[@name='username']"
SET_PASS = "//input[@name='password']"
CLICK_SIGNIN_BTN = "//button[@value='login']"
FORGOT_PASS_HYPERLINK = "//a[contains(text(),'Forgot password?')]"
Authentication_Method = "//select[@name='scheme']"
Select_Authentication_Method = "//option[contains(text(),'Non-J&J')]"
Studied_Dashboard = "(//span[contains(text(),'Studies')])[1]"
Close_Button = "(//button[contains(text(),'Close')])[1]"
Profile_icon = "//i[@class='user outline fitted icon']"
Profile_image = "//div[@class='sc-dxgOiQ hGcaOc']"
Email_id = "//div[@class='userColorIconContainer']"
Change_Pass_Icon = "//i[@class='key icon']"
Change_Pass_Hyper_link = "(//span[contains(text(),'Change password')])[1]"
Username_Email_PopUp = "//div[@class='loginForm']"
Username_Input_Text_Field = "//input[@placeholder='Username']"
Send_Email = "//button[contains(text(),'Send email')]"
LogOut_Icon = "//i[@class='sign out icon']"
LogOut_Hyper_link = "//span[contains(text(),'Log out')]"
Help_Icon = "//i[@class='question circle outline fitted icon']"
About_Halo_link = "//div[@data-test-id='A83_sZ99ii5WTyPOCMu2v']"

